version: '3.9'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.10"

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-net

  flask-prod:
    env_file:
      - .env
    build:
      context: .
      args:
        <<: *build_args
    image: research_assistant-production
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      FLASK_APP: ${FLASK_APP}
      LOG_LEVEL: ${LOG_LEVEL}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      SQLALCHEMY_DATABASE_URI: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
    command: >
      bash -c "while ! nc -z db 5432; do echo 'Waiting for DB...'; sleep 1; done &&
      gunicorn --preload -w ${GUNICORN_WORKERS} -b 0.0.0.0:${PORT} autoapp:app"
    depends_on:
      - db
    networks:
      - shared-net

  flask-test:
    build:
      context: .
      args:
        <<: *build_args
    image: research_assistant-test
    env_file:
      - .env
    environment:
      FLASK_ENV: testing
      FLASK_DEBUG: 1
      FLASK_APP: ${FLASK_APP}
      DATABASE_URL: ${TEST_DATABASE_URL:-sqlite:///:memory:}
      SQLALCHEMY_DATABASE_URI: ${TEST_DATABASE_URL:-sqlite:///:memory:}
      SECRET_KEY: test
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
    depends_on:
      - db
      - flask-prod
    networks:
      - shared-net
    command: >
      pytest --maxfail=1 --disable-warnings --tb=short --cov=research_assistant
    profiles: ["test"]


  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /mnt/api.json
    volumes:
      - ./Api.json:/mnt/api.json:ro
    networks:
      - shared-net
volumes:
  pgdata:

networks:
  shared-net:
    external: true
