name: Flask CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit pytest

      - name: Run Linter (flake8)
        run: |
          echo "Running lint checks..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Security Scan (bandit)
        run: |
          echo "Running security scan..."
          bandit -r . -ll

      - name: Run Tests (pytest)
        run: |
          echo "Running tests..."
          pytest --maxfail=3 --disable-warnings -q
